### ISSUE TITLE
Implicit dependency on SB-POSIX

### ISSUE THREAD

**Issue by quicklisp** [matlisp/matlisp#13]
src/utilities/string.lisp refers to sb-posix, but sb-posix is not in the :depends-on list in the system file. So building from scratch without sb-posix already loaded results in a build failure due to an unknown package.

**Comment by akssri** [comment]
Thanks for reporting this; I've added ```sb-posix``` to the ASDF definitions now.

**Comment by akssri** [comment]
Closing.
