### ISSUE TITLE
matlisp-tests fails - unbound symbol

### ISSUE THREAD

**Issue by quicklisp** [matlisp/matlisp#16]
I get this:

    Unhandled UNBOUND-VARIABLE in thread #<SB-THREAD:THREAD "main thread" RUNNING {10006105B3}>: The variable SRANDN is unbound.

Full log is here: http://report.quicklisp.org/2018-02-26/failure-report/matlisp.html#matlisp-tests

**Comment by akssri** [comment]
Shoot. I replaced the old random number generators with a fancy one.
