### ISSUE TITLE
Conversion of CL arrays to tensors

### ISSUE THREAD

**Issue by bendudson** [matlisp/matlisp#17]
Is there a simple way to convert CL arrays to tensors? Or is there a reader macro to create tensors? It would be nice if functions could accept arrays as inputs, converting to tensors as needed. Is this possible? Thanks!

**Comment by bendudson** [comment]
This seems to do, but is there a way which avoid copying?
`(matlisp:copy #(1 2 3) '#.(tensor 'double-float))`

**Comment by akssri** [comment]
Hmm. You could use the following reader in infix-dispatch-table.
```lisp 
#d[[1, 2]] => (COPY (LIST (LIST 1 2)) '|<BLAS-MIXIN SIMPLE-DENSE-TENSOR: DOUBLE-FLOAT>|)
```
, but this just expands into the form with copy. I can't think of a use case where being slow with such user-input is crucial; even ```make-array``` with ```:initial-contents``` does this.

If you're concerned more about the case where you have a large ```'(simple-array double-float (*))``` and you want to wrap it around with a matlisp-tensor object, that's easy to do (just call ```make-instance```).

**Comment by bendudson** [comment]
Thanks very much! Sorry, for the `make-instance` call, I think I am doing something wrong:

```
(defparameter arr (make-array 6))
(make-instance 'simple-dense-tensor :dimensions 6 :store arr)
```
I get memory fault errors for all inputs I've tried so far, except if the dimensions key is omitted. Thanks for your help!

**Comment by akssri** [comment]
```simple-class-tensor``` is supposed to be an abstract class. You'd do something like,
```lisp
(make-instance (tensor 'double-float) 
    :dimensions  (coerce '(2) '(simple-array index-type (*)))
    :store (make-array 2 :element-type 'double-float))
```

For type ```t``` you can do something like,
```lisp 
 (make-instance (tensor t) :dimensions (idxv 2) :store (make-array 2))
```

**Comment by bendudson** [comment]
Thanks very much for your help!

**Comment by bendudson** [comment]
Sorry... another question. I have a partial solution
```
(defgeneric astensor (object)
  (:documentation "Returns OBJECT as a Matlisp tensor type."))

(defmethod astensor ((object tensor))
  "If already a tensor then just return"
  object)

(defmethod astensor ((object simple-vector))
  "Simple vectors can be used as store for a tensor. 
   The resulting tensor will share storage with the vector."
  (make-instance (tensor (array-element-type object)) 
                 :dimensions  (coerce (array-dimensions object) '(simple-array index-type (*)))
                 :store object))
```

Is it possible to wrap a multidimensional array? The argument to `:store` seems to need to be `simple-vector`, so can't be multidimensional, or a 1D vector displaced to an array:
```
(make-instance (tensor 'double-float) 
    :dimensions  (coerce '(2 2) '(simple-array index-type (*)))
    :store (make-array '(2 2) :element-type 'double-float))
```
gives error
```
The value
  #2A((0.0d0 0.0d0) (0.0d0 0.0d0))
is not of type
  (SIMPLE-ARRAY DOUBLE-FLOAT (*))
```
Is there a way around this?

**Comment by akssri** [comment]
The store are all assumed to be 1-d vectors; the indices are mapped via strides. You can specify this during make-instance; if you leave it out it'll just pick one for you.

```lisp
M> (let ((store (store (range 0d0 16d0))))
     (make-instance (tensor 'double-float) 
		    :dimensions (coerce '(4 4) 'index-store-vector)
		    :store store))
#<|<BLAS-MIXIN SIMPLE-DENSE-TENSOR: DOUBLE-FLOAT>| #(4 4)
  0.000    4.000    8.000    12.00   
  1.000    5.000    9.000    13.00   
  2.000    6.000    10.00    14.00   
  3.000    7.000    11.00    15.00   
>
M> 
;;; from sandbox.lisp
M> (let ((store (store (range 0d0 16d0)))
	 (*default-stride-ordering* :row-major))
     (make-instance (tensor 'double-float) 
		    :dimensions (coerce '(4 4) 'index-store-vector)
		    :store store))
#<|<BLAS-MIXIN SIMPLE-DENSE-TENSOR: DOUBLE-FLOAT>| #(4 4)
  0.000    1.000    2.000    3.000   
  4.000    5.000    6.000    7.000   
  8.000    9.000    10.00    11.00   
  12.00    13.00    14.00    15.00   
>
M> 
```

You can of course specify strides manually.
```lisp
M> (let ((store (store (range 0d0 16d0)))
	 (*default-stride-ordering* :row-major))
     (make-instance (tensor 'double-float) 
		    :dimensions (coerce '(4 4) 'index-store-vector)
		    :strides (coerce '(-1 4) 'index-store-vector)
		    :head 3
		    :store store))
#<|<BLAS-MIXIN SIMPLE-DENSE-TENSOR: DOUBLE-FLOAT>| #(4 4)
  3.000    7.000    11.00    15.00   
  2.000    6.000    10.00    14.00   
  1.000    5.000    9.000    13.00   
  0.000    4.000    8.000    12.00   
>
M> 
```

**Comment by akssri** [comment]
Closing issue.
