### ISSUE TITLE
LU function special variable conflict

### ISSUE THREAD

**Issue by bendudson** [matlisp/matlisp#19]
If `A` is defined with defparameter, then LU decomposition fails:

```
(ql:quickload :matlisp)
(in-package :matlisp)
M> (named-readtables:in-readtable :infix-dispatch-table)
M> (defparameter a 1)
M> (lu (eye '(2 2)))
```
results in an error due to binding A in symbol-macrolet:
```
Form:
  (SYMBOL-MACROLET ((A #:A10))
  (LET ((INFO
         (T/LAPACK-GETRF! |<BLAS-MIXIN SIMPLE-DENSE-TENSOR: DOUBLE-FLOAT>| A
                          (OR (BLAS-MATRIX-COMPATIBLEP A #\N) 0) UPIV)))
...
Compile-time error:
  Attempt to bind a special variable with SYMBOL-MACROLET: A
```

**Comment by bendudson** [comment]
Same happens when following the example
```
#i(/A * b)
```
if A is defined using `defparameter`

**Comment by akssri** [comment]
Thanks for catching this bug (it affects all lapack functions). I'd used a ```symbol-macrolet``` in place of a ```let```; looks like it's fixed now.

**Comment by akssri** [comment]
Issue appears fixed. Closing.
