### ISSUE TITLE
Unable to use package

### ISSUE THREAD

**Issue by dangom** [matlisp/matlisp#2]
When I try to execute any of the examples shown in the README file, I get the following error message:

Will not (yes you read that right, buster!) generate method for abstract tensor class "TENSOR DOUBLE-FLOAT STRIDE-ACCESSOR SIMPLE-ARRAY".
   [Condition of type TENSOR-ABSTRACT-CLASS]

Does matlisp have any dependencies?
I use slime on Emacs, and run SBCL 1.2.11. 

edit: the problem only concerns the last commit.

**Comment by akssri** [comment]
Sorry about that. There was something broken with the type-check in 'tensor-leafp'. 
This should be fixed now.
