### ISSUE TITLE
element-wise operations with reader macro

### ISSUE THREAD

**Issue by bendudson** [matlisp/matlisp#20]
The `#i` reader macro expands `#i(2 * sin(a))` as `(matlisp-user:* 2 (sin a))` so to make this work element-wise over an array`a` the `sin` symbol has to resolve to the function in the `matlisp-user` package. Should users specify `(in-package :matlisp-user)` rather than `(in-package :matlisp)` to use this functionality? Or define their own package using `matlisp`, `matlisp-user` or both packages? Thanks!

**Comment by akssri** [comment]
Good point. It makes sense to default to the shadowed function in ```matlisp-user``` - it's inlined so it's easy to optimize. I have to update ```*operator-assoc-table*``` in the infix reader.
https://github.com/matlisp/matlisp/blob/master/src/reader/infix.lisp#L218

**Comment by akssri** [comment]
Okay, should be fixed now!
