### ISSUE TITLE
Errors using LispWorks on Windows...

### ISSUE THREAD

**Issue by serialhex** [matlisp/matlisp#4]
Hey there.  I've cloned the code, and tried quickloading it, and there are a few errors i'm getting.  The first was an easy - and site-specific - fix, which was

```
**++++ Error in (PACKAGE "MATLISP-FFI"): 
  "FFI" is already a nickname for #<The FOREIGN package, 91/128 internal, 92/128 external>.
```

There is a package named `ffi` in LispWorks, that (I'm guessing, b/c I haven't played with it much) .

The other, more serious problem I'm having is I first get this error when loading `lazy-loader`

```
**++++ Error between functions:
  Call (#<Closure ((#:DISC-ARG-217784)) subfunction of CLOS::GENERIC-FUNCTION-DISCRIMINATOR 22EEC5B2>) has the wrong number of arguments.
```

If I `#+ nil` the `eval-every` in that file, i get a whole bunch more errors... 

```
**++++ Error in (METHOD INITIALIZE-INSTANCE :AFTER (MATLISP::BASE-ACCESSOR)): 
  FIXNUM-SAFETY fell through ECASE expression.
Wanted one of (SAFETY HARLEQUIN-COMMON-LISP:FIXNUM-SAFETY SPEED HARLEQUIN-COMMON-LISP:GC-SAFETY COMPILER::MIGRATABLE (SYSTEM:INTERRUPTIBLE SYSTEM:INTERRUPTABLE) COMPILATION-SPEED SPACE FLOAT DEBUG).

**++++ Error in (DEFCLASS MATLISP:TENSOR): 
  #<STANDARD-CLASS BASE-TENSOR 22DA5CA3> is an invalid superclass of #<TENSOR-CLASS TENSOR 22D821B7>.

**++++ Error in (DEFCLASS MATLISP:STRIDE-TENSOR): 
  #<STANDARD-CLASS STRIDE-ACCESSOR 200DD23B> is an invalid superclass of #<TENSOR-CLASS STRIDE-TENSOR 22D528FB>.

**++++ Error in (DEFCLASS MATLISP:HASH-TENSOR): 
  #<STANDARD-CLASS HASH-TABLE-STORE-MIXIN 200DACB7> is an invalid superclass of #<TENSOR-CLASS HASH-TENSOR 200D219B>.
.

**++++ Error in (DEFCLASS MATLISP:SIMPLE-DENSE-TENSOR): 
  #<STANDARD-CLASS SIMPLE-VECTOR-STORE-MIXIN 200D014B> is an invalid superclass of #<TENSOR-CLASS SIMPLE-DENSE-TENSOR 22D3C0BF>.

**++++ Error in (DEFCLASS MATLISP:GRAPH-TENSOR): 
  #<STANDARD-CLASS GRAPH-ACCESSOR 200C30FF> is an invalid superclass of #<TENSOR-CLASS GRAPH-TENSOR 200B63D7>.

**++++ Error in (DEFCLASS MATLISP:SIMPLE-GRAPH-TENSOR): 
  #<STANDARD-CLASS SIMPLE-VECTOR-STORE-MIXIN 200D014B> is an invalid superclass of #<TENSOR-CLASS SIMPLE-GRAPH-TENSOR 200918B7>.

**++++ Error in (DEFCLASS MATLISP:COORDINATE-TENSOR): 
  #<STANDARD-CLASS COORDINATE-ACCESSOR 200A156F> is an invalid superclass of #<TENSOR-CLASS COORDINATE-TENSOR 20097CB7>.

**++++ Error in (DEFCLASS MATLISP::SIMPLE-COORDINATE-TENSOR): 
  #<STANDARD-CLASS SIMPLE-VECTOR-STORE-MIXIN 200D014B> is an invalid superclass of #<TENSOR-CLASS SIMPLE-COORDINATE-TENSOR 20100837>.
```

From `base-tensor`, which, I'm guessing will just spew out more errors if I do more ignoring of things...  I was under the impression I didn't need BLAS / LAPACK installed in order to use this lib, was that an incorrect assumption?  Let me know if there is anything else you would like me to try out to get it working!  Thanks!

**Comment by akssri** [comment]
Eek. That doesn't look good. Oddly I recall I ended up with something similar when using CCL.

**Comment by akssri** [comment]
I've tracked down the issue that was generating those errors, and partly it was a limitation in closer-mop. 
It seems to kind-of work on CCL now, and I suspect it also should on Lispworks. Can you please check if it works.

You'll need to pull the t2 branch again, and use the following version of closer-mop,
https://github.com/akssri/closer-mop

**Comment by serialhex** [comment]
Nope, unfortunately even with the new closer-mop & rebuilding everything, i get the same error.  I'm including the (verbose) output of rebuilding closer-mop and matlisp, let me know if there is anything you want me to try, as I assume you don't have a copy of lispworks to play with (idk how nerfed the free version is, if you want to try it i'm using 6.1) 

Thanks for looking into this!

[matlisp-borked.txt](https://github.com/matlisp/matlisp/files/302669/matlisp-borked.txt)

**Comment by akssri** [comment]
Hmm. Ignoring the penultimate bug, it looks like this has something to do with loading BLAS and LAPACK on windows. I'm not entirely sure if there's something special that needs to be done for CFFI to load shared libs on Windows.

**Comment by serialhex** [comment]
Okay, so after adding `#+windows"C:\\MinGW\\lib\\"` to that file, and `"C:\MinGW\bin"` to my PATH in windows, i get that second error above.  It does seem to be loading BLAS & LAPACK, as CFFI was being all 'y u no haz MinGW dll?' after I added that line to the file and before I added the `bin` dir to my path (and rebooted, b/c you always reboot whenever you do anything on windows!)  CFFI isn't giving me any more problems, but this is... :confused: 

current mess:  [matlisp-borked2.txt](https://github.com/matlisp/matlisp/files/303026/matlisp-borked2.txt)
(i figure this is nicer than huge text dumps in the threads... and your email!)

**Comment by akssri** [comment]
I tried getting Lispworks 6.1 to run, but it complains from the get go about missing ASDF 3 support.

**Comment by serialhex** [comment]
Ehhhhh... I forgot about that mess... It was a bit hard for me to get it running smoothly myself.  If it wasn't b/d we need it for its excellent COM support we'd be using SBCL or Clozure or something...  I have my `.lispworks` file load the latest asdf using `(load ...)` which then bypasses the old asdf they have included.

I'm sorry for the pain, I'll continue to try and get it working properly if it's getting to be too much for you.  Thanks for the help thus far though!

**Comment by akssri** [comment]
That's probably going to be hard, since neither Matlisp nor MOP has ready documentation :)
Can you email me the asdf-3 hack ? I'll try and take a look at it.

**Comment by serialhex** [comment]
It's not really a "hack", as it is a workaround Lisp Distros being behind on the times.  I have a copy of the latest `asdf.lisp` file in my `$HOME` dir, and then I have this is my `.lispworks` file: `(load (merge-pathnames "asdf" (user-homedir-pathname)))` (to be honest, I do the same thing in Linux, I just have one `.lisprc.lisp` file and symlink `.eclrc`, `.sbclrc` `.cclrc` or whatever they all are to it)

I also have the normal quicklisp stuff in there too, after loading asdf.  Doing that *should* get you up and running... If not let me know!

**Comment by akssri** [comment]
The latest asdf.lisp from which implementation though ? Lispworks Pro ?

**Comment by serialhex** [comment]
-_- dumb lispworks! try this in your .lispworks file: `(setf system:*stack-overflow-behaviour* :warn)` and i'm using the vanilla asdf.lisp file from the asdf people themselves.  I'm not sure if that snippit of code will help, but it may.

**Comment by akssri** [comment]
Is there some to make PE to allow me to use SLIME ?

**Comment by serialhex** [comment]
Ahh, now *that* is a hack... kinda.  The easy way (and probably the only way unless you want to pend $$$$$ on a license) is to load up the IDE, and then `(load "/path/to/start-swank.lisp")` and have fun from there. The other way is to make an executable with just a lisp image, which if you really want to know I can relate the details, but I'm pretty sure the free version of LispWorks doesn't allow you to make executables.  So yeah, simply `load`-ing the swank stuff should get you up & running.
