### ISSUE TITLE
Utility Cleanup

### ISSUE THREAD

**Issue by tarballs-are-good** [matlisp/matlisp#9]
Alexandria provides many utilities. At least the following can be replaced.

- [x] `with-gensyms`
- [x] `define-constant`
- [x] `if-let`
- [x] `when-let`
- [x] `curry`
- [x] `flatten`
- [x] `ensure-list`

Some utilities can be made simpler (non-exhaustive list).

- [x] `copy-n`

**Comment by akssri** [comment]
I've removed the duplicate definitions provided by Alexandria. I'm not entirely sure what you mean by "made simpler" under ```copy-n```.

**Comment by tarballs-are-good** [comment]
COPY-N can just use SUBSEQ, no?

Definitely keep the name COPY-N, but I think the implementation is a single function call.

**Comment by akssri** [comment]
Yeah, I did a ```grep -ilr`` and many old utilities seemed superfluous. Any others ?
